
name: CI_RENTALX
# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
        
      - name: Install Dependecies
        run: yarn
        
      - name: Build
        run: yarn build
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}}
          source: "., !node_modules"
          target: "~/app/rentalx"
          
      - name: Update API command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}}
          script: |
            cd ~/app/rentalx
            yarn 
            ./node_modules/.bin/typeorm migration:run
             pm2 restart rentalx_api
